### Inspect scraped data_files

In [2]:
import pandas as pd
from itertools import combinations

In [3]:
logboek_df = pd.read_csv('logboek.csv', sep=';')
countries = logboek_df["land"].tolist()
leagues = logboek_df["competitienaam"].tolist()
seasons = logboek_df["jaar"].tolist()

In [4]:
print(countries)

['england', 'mexico', 'japan', 'iran', 'south-korea', 'australia', 'morocco', 'senegal', 'nigeria', 'algeria', 'egypt', 'ivory-coast', 'usa', 'canada', 'panama', 'argentina', 'brazil', 'colombia', 'uruguay', 'ecuador', 'paraguay', 'austria', 'belgium', 'cyprus', 'czech-republic', 'france', 'germany', 'hungary', 'ireland', 'italy', 'luxembourg', 'malta', 'netherlands', 'northern-ireland', 'norway', 'poland', 'portugal', 'romania', 'russia', 'scotland', 'slovakia', 'spain', 'switzerland', 'turkey', 'wales', 'croatia', 'denmark', 'ukraine', 'serbia', 'sweden']

### checked up untill index 0

In [5]:
def filter_rounds(df):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str.startswith("Round ")].reset_index(drop=True)
    return return_df

In [6]:
def filter_playoffs(df, start_round_playoffs):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str[6:].astype(int) < start_round_playoffs].reset_index(drop=True)
    return return_df

In [55]:
def filter_on_date(df, start_date, keep_before = True):
    """ 
    Format start_date: "YYYY-MM-DD"
    """
    return_df = df.copy()
    start_date = pd.to_datetime(start_date)
    
    return_df["date"] = pd.to_datetime(return_df["date"], format="%d.%m.%Y", errors='coerce')
    
    if keep_before:
        return_df = return_df[(return_df["date"] < start_date)].reset_index(drop=True)
    else:
        return_df = return_df[(return_df["date"] >= start_date)].reset_index(drop=True)
    return return_df

In [93]:
def fill_in_forfaits(df):
    return_df = df.copy()
    
    forfait_indices = return_df[return_df["team_home"] == "Awrd"].index
    
    for idx in forfait_indices:
        parts = return_df.loc[idx, "full_text"].split(" | ")
        return_df.loc[idx, "team_home"] = parts[2]
        return_df.loc[idx, "team_away"] = parts[3]
    
    return return_df

In [9]:
def remove_round_prefix(df):
    return_df = df.copy()
    return_df["round"] = return_df["round"].apply(lambda x: x[6:])
    return return_df

In [10]:
def check_specific_match(df, team1, team2):
    return df[((df["team_home"] == team1) & (df["team_away"] == team2)) | ((df["team_home"] == team2) & (df["team_away"] == team1))]

In [11]:
def check_rounds(df):
    rounds = df["round"].unique().tolist()
    counted_rounds = df["round"].value_counts().to_dict()

    # check if all rounds appear the same amount of times
    rounds_appear_same_amount = len(set(counted_rounds.values())) == 1

    # check if rounds start with "Round"
    rounds_start_with_round = all(r.startswith("Round") for r in rounds)

    print(f"Rounds: {rounds}")
    print(f"Only normal rounds: {rounds_start_with_round}")
    print(f"All rounds appear same amount of times: {rounds_appear_same_amount}")

In [78]:
def check_teams(df):
    home_teams = df["team_home"].unique().tolist()
    away_teams = df["team_away"].unique().tolist()

    all_teams = set(home_teams) | set(away_teams)
    print(f"Teams: {all_teams}")
    print(f"Number of teams: {len(all_teams)}")

    # check if all teams appear in both home and away the same amount of times
    home_team_counts = df["team_home"].value_counts().to_dict()
    away_team_counts = df["team_away"].value_counts().to_dict()
    teams_appear_same_amount = all(home_team_counts.get(team, 0) == away_team_counts.get(team, 0) for team in all_teams)
    print(f"All teams appear same amount of times in home and away: {teams_appear_same_amount}")
    if teams_appear_same_amount:
        print(f"Each team appears {home_team_counts[home_teams[0]]} times in home and away")
    elif len(all_teams) % 2 == 0:
        rand_team = list(all_teams)[0]
        expected_h_games = (home_team_counts[rand_team] + away_team_counts[rand_team]) / 2
        print("Teams that don't play the expected amount at home")
        for key, value in home_team_counts.items():
            if value != expected_h_games:
                print(f"{key}: {value}")
        
        print()
        print("Amount of times teams played away")
        for key, value in away_team_counts.items():
           if value != expected_h_games:
                print(f"{key}: {value}")
    
    else:
        print(f"Odd number of teams: {len(all_teams)}")

In [13]:
def check_games(df):
    teams = sorted(set(df['team_home'].unique()) | set(df['team_away'].unique()))
    
    # Build symmetric n x n matrix
    matrix = pd.DataFrame(0, index=teams, columns=teams)
    
    for _, row in df.iterrows():
        h, a = row['team_home'], row['team_away']
        matrix.loc[h, a] += 1
        matrix.loc[a, h] += 1  # symmetric: home/away doesn't matter
    
    # Extract counts for all unique pairs (upper triangle)
    pair_counts = {
        (t1, t2): matrix.loc[t1, t2]
        for t1, t2 in combinations(teams, 2)
    }
    
    unique_counts = set(pair_counts.values())
    is_balanced = len(unique_counts) == 1 and 0 not in unique_counts
    
    print("=== Game Balance Check ===\n")
    print("Head-to-head matrix:")
    print(matrix.to_string())
    print()
    
    count_freq = {}
    for v in pair_counts.values():
        count_freq[v] = count_freq.get(v, 0) + 1
    
    if is_balanced:
        times = unique_counts.pop()
        print(f"Balanced: every pair plays exactly {times} time(s).")
    else:
        print(f"Not balanced. Distribution of matchup counts: {count_freq}")
        if 0 in unique_counts:
            missing = [f"{t1} vs {t2}" for (t1, t2), v in pair_counts.items() if v == 0]
            print(f"   Never played: {missing[:10]}{'...' if len(missing) > 10 else ''}")
        modal = max(set(pair_counts.values()), key=list(pair_counts.values()).count)
        odd = {f"{k[0]} vs {k[1]}": v for k, v in pair_counts.items() if v != modal}
        if odd:
            print(f"   Odd counts: {odd}")

In [105]:
# Checked untill index 10, egypt
index = 18
country = countries[index]
league = leagues[index]
season = seasons[index]
print(country)
print(league)
print(season)
filename = f"{country}_{league}_{season}.csv"
df = pd.read_csv(f"./scraped_data/{filename}")
df = fill_in_forfaits(df)
df

uruguay
liga-auf-uruguaya
2025

,round,date,team_home,team_away,full_text
0,Final,30.11.2025,AET,Nacional,30.11.2025 | AET | Nacional | Winner: Nacional...
1,Final,23.11.2025,Penarol,Nacional,23.11.2025 | Penarol | Nacional | 2 | 2
2,Semi-finals,16.11.2025,AET,Liverpool M.,16.11.2025 | AET | Liverpool M. | Penarol | Ad...
3,Round 15,09.11.2025,Defensor Sp.,Nacional,09.11.2025 | Defensor Sp. | Nacional | 1 | 1
4,Round 15,09.11.2025,Juventud,Progreso,09.11.2025 | Juventud | Progreso | 1 | 1
...,...,...,...,...,...
295,Round 1,02.02.2025,Miramar,Plaza Colonia,02.02.2025 | Miramar | Plaza Colonia | 0 | 1
296,Round 1,02.02.2025,Progreso,Penarol,02.02.2025 | Progreso | Penarol | 1 | 3
297,Round 1,01.02.2025,Danubio,Liverpool M.,01.02.2025 | Danubio | Liverpool M. | 1 | 1
298,Round 1,01.02.2025,Defensor Sp.,Boston River,01.02.2025 | Defensor Sp. | Boston River | 2 | 0
299,Round 1,31.01.2025,Cerro Largo,Juventud,31.01.2025 | Cerro Largo | Juventud | 1 | 1

In [97]:
# First do the checks, then do the filtering and removing of round prefix if necessary

check_rounds(df)
check_teams(df)
check_games(df)

Rounds: ['Final', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1', 'Round 20', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 14', 'Round 15', 'Round 11', 'Round 13', 'Round 12', 'Round 10', 'Round 9', 'Round 8', 'Round 7']
Only normal rounds: False
All rounds appear same amount of times: False
Teams: {'Ind. Medellin', 'Junior', 'Aguilas', 'America De Cali', 'Dep. Cali', 'Dep. Pasto', 'Bucaramanga', 'Once Caldas', 'Atl. Nacional', 'Deportes Tolima', 'Santa Fe', 'Alianza', 'Envigado', 'Llaneros', 'Chico', 'Millonarios', 'U. Magdalena', 'Inter Bogotá', 'Pereira', 'Fortaleza'}
Number of teams: 20
All teams appear same amount of times in home and away: True
Each team appears 27 times in home and away
=== Game Balance Check ===

Head-to-head matrix:
                 Aguilas  Alianza  America De Cali  Atl. Nacional  Bucaramanga  Chico  Dep. Cali  Dep. Pasto  Deportes Tolima  Envigado  Fortaleza  Ind. Medellin  Inter Bogotá  Junior  Llaneros  Millonarios  Once Caldas  Pereira  Santa Fe  U. Magdalena
Aguilas                0        2                2              2            2      2          2           2                2         4          2              2             2       2         2            2            2        2         2             2
Alianza                2        0                2              2            4      2          2           2                2         2          2              2             2       2         2            2            2        2         2             2
America De Cali        2        2                0              4            2      2          4           2                4         2          2              6             2       6         2            2            2        2         2             2
Atl. Nacional          2        2                4              0            2      2          2           2                2         2          2              6             2       4         2            4            4        2         4             2
Bucaramanga            2        4                2              2            0      2          2           2                4         2          4              2             2       2         2            2            2        2         4             2
Chico                  2        2                2              2            2      0          2           4                2         2          2              2             2       2         2            2            2        2         2             2
Dep. Cali              2        2                4              2            2      2          0           2                2         2          2              2             2       2         2            2            2        2         2             2
Dep. Pasto             2        2                2              2            2      4          2           0                2         2          2              2             2       2         2            2            2        2         2             2
Deportes Tolima        2        2                4              2            4      2          2           2                0         2          4              4             2       6         4            2            2        2         4             2
Envigado               4        2                2              2            2      2          2           2                2         0          2              2             2       2         2            2            2        2         2             2
Fortaleza              2        2                2              2            4      2          2           2                4         2          0              2             4       2         2            2            2        2         4             2
Ind. Medellin          2        2                6              6            2      2          2           2                4         2          2              0             2       6         2            2            2        2         4             2
Inter Bogotá           2        2                2              2            2      2          2           2                2         2          4              2             0       2         2            2            2        2         2             2
Junior                 2        2                6              4            2      2          2           2                6         2          2              6             2       0         2            2            2        2         2             4
Llaneros               2        2                2              2            2      2          2           2                4         2          2              2             2       2         0            2            2        2         2             2
Millonarios            2        2                2              4            2      2          2           2                2         2          2              2             2       2         2            0            4        2         6             2
Once Caldas            2        2                2              4            2      2          2           2                2         2          2              2             2       2         2            4            0        4         4             2
Pereira                2        2                2              2            2      2          2           2                2         2          2              2             2       2         2            2            4        0         2             2
Santa Fe               2        2                2              4            4      2          2           2                4         2          4              4             2       2         2            6            4        2         0             2
U. Magdalena           2        2                2              2            2      2          2           2                2         2          2              2             2       4         2            2            2        2         2             0

Not balanced. Distribution of matchup counts: {np.int64(2): 160, np.int64(4): 24, np.int64(6): 6}
   Odd counts: {'Aguilas vs Envigado': np.int64(4), 'Alianza vs Bucaramanga': np.int64(4), 'America De Cali vs Atl. Nacional': np.int64(4), 'America De Cali vs Dep. Cali': np.int64(4), 'America De Cali vs Deportes Tolima': np.int64(4), 'America De Cali vs Ind. Medellin': np.int64(6), 'America De Cali vs Junior': np.int64(6), 'Atl. Nacional vs Ind. Medellin': np.int64(6), 'Atl. Nacional vs Junior': np.int64(4), 'Atl. Nacional vs Millonarios': np.int64(4), 'Atl. Nacional vs Once Caldas': np.int64(4), 'Atl. Nacional vs Santa Fe': np.int64(4), 'Bucaramanga vs Deportes Tolima': np.int64(4), 'Bucaramanga vs Fortaleza': np.int64(4), 'Bucaramanga vs Santa Fe': np.int64(4), 'Chico vs Dep. Pasto': np.int64(4), 'Deportes Tolima vs Fortaleza': np.int64(4), 'Deportes Tolima vs Ind. Medellin': np.int64(4), 'Deportes Tolima vs Junior': np.int64(6), 'Deportes Tolima vs Llaneros': np.int64(4), 'Deportes Tolima vs Santa Fe': np.int64(4), 'Fortaleza vs Inter Bogotá': np.int64(4), 'Fortaleza vs Santa Fe': np.int64(4), 'Ind. Medellin vs Junior': np.int64(6), 'Ind. Medellin vs Santa Fe': np.int64(4), 'Junior vs U. Magdalena': np.int64(4), 'Millonarios vs Once Caldas': np.int64(4), 'Millonarios vs Santa Fe': np.int64(6), 'Once Caldas vs Pereira': np.int64(4), 'Once Caldas vs Santa Fe': np.int64(4)}

In [81]:
# write away cleaned df and adapt logboek
df = remove_round_prefix(df)
df.to_csv(f"./cleaned_data/{filename}", index=False)

In [106]:
df_only_rounds = filter_rounds(df)

In [107]:
check_rounds(df_only_rounds)
check_teams(df_only_rounds)
check_games(df_only_rounds)

Rounds: ['Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: False
Teams: {'Juventud', 'Liverpool M.', 'Danubio', 'Racing Montevideo', 'Plaza Colonia', 'Montevideo City', 'Wanderers', 'CA Cerro', 'Penarol', 'Boston River', 'Defensor Sp.', 'Nacional', 'Miramar', 'Cerro Largo', 'River Plate', 'Progreso'}
Number of teams: 16
All teams appear same amount of times in home and away: False
Teams that don't play the expected amount at home
Defensor Sp.: 19
Juventud: 19
Cerro Largo: 19
Penarol: 19
Racing Montevideo: 19
Liverpool M.: 19
Nacional: 19
Boston River: 19
Montevideo City: 18
CA Cerro: 18
Wanderers: 18
Danubio: 18
Miramar: 18
Plaza Colonia: 18
River Plate: 18
Progreso: 18

Amount of times teams played away
Progreso: 19
River Plate: 19
Plaza Colonia: 19
Danubio: 19
Miramar: 19
Montevideo City: 19
Wanderers: 19
CA Cerro: 19
Nacional: 18
Penarol: 18
Boston River: 18
Liverpool M.: 18
Racing Montevideo: 18
Cerro Largo: 18
Defensor Sp.: 18
Juventud: 18
=== Game Balance Check ===

Head-to-head matrix:
                   Boston River  CA Cerro  Cerro Largo  Danubio  Defensor Sp.  Juventud  Liverpool M.  Miramar  Montevideo City  Nacional  Penarol  Plaza Colonia  Progreso  Racing Montevideo  River Plate  Wanderers
Boston River                  0         2            2        3             2         3             2        3                3         3        2              2         3                  3            2          2
CA Cerro                      2         0            3        2             3         2             3        2                2         2        3              3         2                  2            3          3
Cerro Largo                   2         3            0        2             3         2             3        2                2         2        3              3         2                  2            3          3
Danubio                       3         2            2        0             2         3             2        3                3         3        2              2         3                  3            2          2
Defensor Sp.                  2         3            3        2             0         2             3        2                2         2        3              3         2                  2            3          3
Juventud                      3         2            2        3             2         0             2        3                3         3        2              2         3                  3            2          2
Liverpool M.                  2         3            3        2             3         2             0        2                2         2        3              3         2                  2            3          3
Miramar                       3         2            2        3             2         3             2        0                3         3        2              2         3                  3            2          2
Montevideo City               3         2            2        3             2         3             2        3                0         3        2              2         3                  3            2          2
Nacional                      3         2            2        3             2         3             2        3                3         0        2              2         3                  3            2          2
Penarol                       2         3            3        2             3         2             3        2                2         2        0              3         2                  2            3          3
Plaza Colonia                 2         3            3        2             3         2             3        2                2         2        3              0         2                  2            3          3
Progreso                      3         2            2        3             2         3             2        3                3         3        2              2         0                  3            2          2
Racing Montevideo             3         2            2        3             2         3             2        3                3         3        2              2         3                  0            2          2
River Plate                   2         3            3        2             3         2             3        2                2         2        3              3         2                  2            0          3
Wanderers                     2         3            3        2             3         2             3        2                2         2        3              3         2                  2            3          0

Not balanced. Distribution of matchup counts: {np.int64(2): 64, np.int64(3): 56}
   Odd counts: {'Boston River vs Danubio': np.int64(3), 'Boston River vs Juventud': np.int64(3), 'Boston River vs Miramar': np.int64(3), 'Boston River vs Montevideo City': np.int64(3), 'Boston River vs Nacional': np.int64(3), 'Boston River vs Progreso': np.int64(3), 'Boston River vs Racing Montevideo': np.int64(3), 'CA Cerro vs Cerro Largo': np.int64(3), 'CA Cerro vs Defensor Sp.': np.int64(3), 'CA Cerro vs Liverpool M.': np.int64(3), 'CA Cerro vs Penarol': np.int64(3), 'CA Cerro vs Plaza Colonia': np.int64(3), 'CA Cerro vs River Plate': np.int64(3), 'CA Cerro vs Wanderers': np.int64(3), 'Cerro Largo vs Defensor Sp.': np.int64(3), 'Cerro Largo vs Liverpool M.': np.int64(3), 'Cerro Largo vs Penarol': np.int64(3), 'Cerro Largo vs Plaza Colonia': np.int64(3), 'Cerro Largo vs River Plate': np.int64(3), 'Cerro Largo vs Wanderers': np.int64(3), 'Danubio vs Juventud': np.int64(3), 'Danubio vs Miramar': np.int64(3), 'Danubio vs Montevideo City': np.int64(3), 'Danubio vs Nacional': np.int64(3), 'Danubio vs Progreso': np.int64(3), 'Danubio vs Racing Montevideo': np.int64(3), 'Defensor Sp. vs Liverpool M.': np.int64(3), 'Defensor Sp. vs Penarol': np.int64(3), 'Defensor Sp. vs Plaza Colonia': np.int64(3), 'Defensor Sp. vs River Plate': np.int64(3), 'Defensor Sp. vs Wanderers': np.int64(3), 'Juventud vs Miramar': np.int64(3), 'Juventud vs Montevideo City': np.int64(3), 'Juventud vs Nacional': np.int64(3), 'Juventud vs Progreso': np.int64(3), 'Juventud vs Racing Montevideo': np.int64(3), 'Liverpool M. vs Penarol': np.int64(3), 'Liverpool M. vs Plaza Colonia': np.int64(3), 'Liverpool M. vs River Plate': np.int64(3), 'Liverpool M. vs Wanderers': np.int64(3), 'Miramar vs Montevideo City': np.int64(3), 'Miramar vs Nacional': np.int64(3), 'Miramar vs Progreso': np.int64(3), 'Miramar vs Racing Montevideo': np.int64(3), 'Montevideo City vs Nacional': np.int64(3), 'Montevideo City vs Progreso': np.int64(3), 'Montevideo City vs Racing Montevideo': np.int64(3), 'Nacional vs Progreso': np.int64(3), 'Nacional vs Racing Montevideo': np.int64(3), 'Penarol vs Plaza Colonia': np.int64(3), 'Penarol vs River Plate': np.int64(3), 'Penarol vs Wanderers': np.int64(3), 'Plaza Colonia vs River Plate': np.int64(3), 'Plaza Colonia vs Wanderers': np.int64(3), 'Progreso vs Racing Montevideo': np.int64(3), 'River Plate vs Wanderers': np.int64(3)}

In [117]:
# write away cleaned df and adapt logboek
df_only_rounds = remove_round_prefix(df_only_rounds)
df_only_rounds.to_csv(f"./cleaned_data/{filename}", index=False)

In [111]:
df_only_rounds = filter_playoffs(df_only_rounds, 31)

In [ ]:
df_only_rounds[df_only_rounds["round"] == "Round 1"]

In [108]:
df_filtered = filter_on_date(df_only_rounds, "2025-08-01", keep_before=False)

In [101]:
df_filtered = filter_on_date(df_only_rounds, "2025-11-18", keep_before=True)

In [109]:
df_filtered

,round,date,team_home,team_away,full_text
0,Round 15,2025-11-09,Defensor Sp.,Nacional,09.11.2025 | Defensor Sp. | Nacional | 1 | 1
1,Round 15,2025-11-09,Juventud,Progreso,09.11.2025 | Juventud | Progreso | 1 | 1
2,Round 15,2025-11-09,Montevideo City,Penarol,09.11.2025 | Montevideo City | Penarol | 0 | 2
3,Round 15,2025-11-09,CA Cerro,Boston River,09.11.2025 | CA Cerro | Boston River | 0 | 0
4,Round 15,2025-11-08,Wanderers,River Plate,08.11.2025 | Wanderers | River Plate | 0 | 4
...,...,...,...,...,...
115,Round 1,2025-08-03,Boston River,Defensor Sp.,03.08.2025 | Boston River | Defensor Sp. | 4 | 0
116,Round 1,2025-08-02,Nacional,Montevideo City,02.08.2025 | Nacional | Montevideo City | 5 | 2
117,Round 1,2025-08-02,River Plate,CA Cerro,02.08.2025 | River Plate | CA Cerro | 0 | 0
118,Round 1,2025-08-02,Juventud,Cerro Largo,02.08.2025 | Juventud | Cerro Largo | 0 | 2
119,Round 1,2025-08-02,Penarol,Progreso,02.08.2025 | Penarol | Progreso | 2 | 1

In [110]:
check_rounds(df_filtered)
check_teams(df_filtered)   
check_games(df_filtered)

Rounds: ['Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Juventud', 'Liverpool M.', 'Danubio', 'Racing Montevideo', 'Plaza Colonia', 'Montevideo City', 'Wanderers', 'CA Cerro', 'Penarol', 'Boston River', 'Defensor Sp.', 'Nacional', 'Miramar', 'Cerro Largo', 'River Plate', 'Progreso'}
Number of teams: 16
All teams appear same amount of times in home and away: False
Teams that don't play the expected amount at home
Juventud: 8
Montevideo City: 8
CA Cerro: 8
Plaza Colonia: 8
Penarol: 8
Racing Montevideo: 8
River Plate: 8
Liverpool M.: 8
Defensor Sp.: 7
Wanderers: 7
Danubio: 7
Cerro Largo: 7
Miramar: 7
Progreso: 7
Nacional: 7
Boston River: 7

Amount of times teams played away
Nacional: 8
Progreso: 8
Boston River: 8
Cerro Largo: 8
Defensor Sp.: 8
Danubio: 8
Miramar: 8
Wanderers: 8
Penarol: 7
River Plate: 7
Plaza Colonia: 7
Liverpool M.: 7
Racing Montevideo: 7
Juventud: 7
Montevideo City: 7
CA Cerro: 7
=== Game Balance Check ===

Head-to-head matrix:
                   Boston River  CA Cerro  Cerro Largo  Danubio  Defensor Sp.  Juventud  Liverpool M.  Miramar  Montevideo City  Nacional  Penarol  Plaza Colonia  Progreso  Racing Montevideo  River Plate  Wanderers
Boston River                  0         1            1        1             1         1             1        1                1         1        1              1         1                  1            1          1
CA Cerro                      1         0            1        1             1         1             1        1                1         1        1              1         1                  1            1          1
Cerro Largo                   1         1            0        1             1         1             1        1                1         1        1              1         1                  1            1          1
Danubio                       1         1            1        0             1         1             1        1                1         1        1              1         1                  1            1          1
Defensor Sp.                  1         1            1        1             0         1             1        1                1         1        1              1         1                  1            1          1
Juventud                      1         1            1        1             1         0             1        1                1         1        1              1         1                  1            1          1
Liverpool M.                  1         1            1        1             1         1             0        1                1         1        1              1         1                  1            1          1
Miramar                       1         1            1        1             1         1             1        0                1         1        1              1         1                  1            1          1
Montevideo City               1         1            1        1             1         1             1        1                0         1        1              1         1                  1            1          1
Nacional                      1         1            1        1             1         1             1        1                1         0        1              1         1                  1            1          1
Penarol                       1         1            1        1             1         1             1        1                1         1        0              1         1                  1            1          1
Plaza Colonia                 1         1            1        1             1         1             1        1                1         1        1              0         1                  1            1          1
Progreso                      1         1            1        1             1         1             1        1                1         1        1              1         0                  1            1          1
Racing Montevideo             1         1            1        1             1         1             1        1                1         1        1              1         1                  0            1          1
River Plate                   1         1            1        1             1         1             1        1                1         1        1              1         1                  1            0          1
Wanderers                     1         1            1        1             1         1             1        1                1         1        1              1         1                  1            1          0

Balanced: every pair plays exactly 1 time(s).

In [75]:
check_specific_match(df_filtered, "Veraguas", "Tauro")

,round,date,team_home,team_away,full_text
53,Round 8,2025-09-13,Tauro,Veraguas,13.09.2025 | Tauro | Veraguas | 1 | 3

In [104]:
df_filtered = remove_round_prefix(df_filtered)
df_filtered.to_csv(f"./cleaned_data/{filename}", index=False)