### Inspect scraped data_files

In [2]:
import pandas as pd
from itertools import combinations

In [3]:
logboek_df = pd.read_csv('logboek.csv', sep=';')
countries = logboek_df["land"].tolist()
leagues = logboek_df["competitienaam"].tolist()
seasons = logboek_df["jaar"].tolist()

In [4]:
print(countries)

['england', 'mexico', 'japan', 'iran', 'south-korea', 'australia', 'morocco', 'senegal', 'nigeria', 'algeria', 'egypt', 'ivory-coast', 'usa', 'canada', 'panama', 'argentina', 'brazil', 'colombia', 'uruguay', 'ecuador', 'paraguay', 'austria', 'belgium', 'cyprus', 'czech-republic', 'france', 'germany', 'hungary', 'ireland', 'italy', 'luxembourg', 'malta', 'netherlands', 'northern-ireland', 'norway', 'poland', 'portugal', 'romania', 'russia', 'scotland', 'slovakia', 'spain', 'switzerland', 'turkey', 'wales', 'croatia', 'denmark', 'ukraine', 'serbia', 'sweden']

### checked up untill index 0

In [5]:
def filter_rounds(df):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str.startswith("Round ")].reset_index(drop=True)
    return return_df

In [6]:
def filter_playoffs(df, start_round_playoffs):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str[6:].astype(int) < start_round_playoffs].reset_index(drop=True)
    return return_df

In [7]:
def filter_on_date(df, start_date, keep_before = True):
    """ 
    Format start_date: "YYYY-MM-DD"
    """
    return_df = df.copy()
    start_date = pd.to_datetime(start_date)
    
    return_df["date"] = pd.to_datetime(return_df["date"], errors='coerce')
    if keep_before:
        return_df = return_df[(return_df["date"] < start_date)].reset_index(drop=True)
    else:
        return_df = return_df[(return_df["date"] >= start_date)].reset_index(drop=True)
    return return_df

In [8]:
def fill_in_forfaits(df):
    return_df = df.copy()
    # Identify matches with missing scores
    try:
        index_forfait = return_df[return_df["team_home"] == "Awrd"].index[0]
        parts = return_df.loc[index_forfait, "full_text"].split(" | ")
        return_df.loc[index_forfait, "team_home"] = parts[2]
        return_df.loc[index_forfait, "team_away"] = parts[3]
        return return_df
    except:
        return df

In [9]:
def remove_round_prefix(df):
    return_df = df.copy()
    return_df["round"] = return_df["round"].apply(lambda x: x[6:])
    return return_df

In [10]:
def check_specific_match(df, team1, team2):
    return df[((df["team_home"] == team1) & (df["team_away"] == team2)) | ((df["team_home"] == team2) & (df["team_away"] == team1))]

In [11]:
def check_rounds(df):
    rounds = df["round"].unique().tolist()
    counted_rounds = df["round"].value_counts().to_dict()

    # check if all rounds appear the same amount of times
    rounds_appear_same_amount = len(set(counted_rounds.values())) == 1

    # check if rounds start with "Round"
    rounds_start_with_round = all(r.startswith("Round") for r in rounds)

    print(f"Rounds: {rounds}")
    print(f"Only normal rounds: {rounds_start_with_round}")
    print(f"All rounds appear same amount of times: {rounds_appear_same_amount}")

In [12]:
def check_teams(df):
    home_teams = df["team_home"].unique().tolist()
    away_teams = df["team_away"].unique().tolist()

    all_teams = set(home_teams) | set(away_teams)
    print(f"Teams: {all_teams}")
    print(f"Number of teams: {len(all_teams)}")

    # check if all teams appear in both home and away the same amount of times
    home_team_counts = df["team_home"].value_counts().to_dict()
    away_team_counts = df["team_away"].value_counts().to_dict()
    teams_appear_same_amount = all(home_team_counts.get(team, 0) == away_team_counts.get(team, 0) for team in all_teams)
    print(f"All teams appear same amount of times in home and away: {teams_appear_same_amount}")
    if teams_appear_same_amount:
        print(f"Each team appears {home_team_counts[home_teams[0]]} times in home and away")

In [13]:
def check_games(df):
    teams = sorted(set(df['team_home'].unique()) | set(df['team_away'].unique()))
    
    # Build symmetric n x n matrix
    matrix = pd.DataFrame(0, index=teams, columns=teams)
    
    for _, row in df.iterrows():
        h, a = row['team_home'], row['team_away']
        matrix.loc[h, a] += 1
        matrix.loc[a, h] += 1  # symmetric: home/away doesn't matter
    
    # Extract counts for all unique pairs (upper triangle)
    pair_counts = {
        (t1, t2): matrix.loc[t1, t2]
        for t1, t2 in combinations(teams, 2)
    }
    
    unique_counts = set(pair_counts.values())
    is_balanced = len(unique_counts) == 1 and 0 not in unique_counts
    
    print("=== Game Balance Check ===\n")
    print("Head-to-head matrix:")
    print(matrix.to_string())
    print()
    
    count_freq = {}
    for v in pair_counts.values():
        count_freq[v] = count_freq.get(v, 0) + 1
    
    if is_balanced:
        times = unique_counts.pop()
        print(f"Balanced: every pair plays exactly {times} time(s).")
    else:
        print(f"Not balanced. Distribution of matchup counts: {count_freq}")
        if 0 in unique_counts:
            missing = [f"{t1} vs {t2}" for (t1, t2), v in pair_counts.items() if v == 0]
            print(f"   Never played: {missing[:10]}{'...' if len(missing) > 10 else ''}")
        modal = max(set(pair_counts.values()), key=list(pair_counts.values()).count)
        odd = {f"{k[0]} vs {k[1]}": v for k, v in pair_counts.items() if v != modal}
        if odd:
            print(f"   Odd counts: {odd}")

In [25]:
# Checked untill index 10, egypt
index = 20
country = countries[index]
league = leagues[index]
season = seasons[index]
print(country)
print(league)
print(season)
filename = f"{country}_{league}_{season}.csv"
df = pd.read_csv(f"./scraped_data/{filename}")
df = fill_in_forfaits(df)
df

paraguay
copa-de-primera
2025

,round,date,team_home,team_away,full_text
0,Round 22,30.11.2025,Atl. Tembetary,Cerro Porteno,30.11.2025 | Atl. Tembetary | Cerro Porteno | ...
1,Round 22,30.11.2025,Guarani,Sp. Luqueno,30.11.2025 | Guarani | Sp. Luqueno | 2 | 1
2,Round 22,28.11.2025,Recoleta,Nacional Asuncion,28.11.2025 | Recoleta | Nacional Asuncion | 0 | 0
3,Round 22,27.11.2025,Libertad Asuncion,General Caballero JLM,27.11.2025 | Libertad Asuncion | General Cabal...
4,Round 22,26.11.2025,Olimpia Asuncion,2 de Mayo,26.11.2025 | Olimpia Asuncion | 2 de Mayo | 3 | 3
...,...,...,...,...,...
259,Round 1,26.01.2025,Olimpia Asuncion,Guarani,26.01.2025 | Olimpia Asuncion | Guarani | 0 | 1
260,Round 1,25.01.2025,General Caballero JLM,Recoleta,25.01.2025 | General Caballero JLM | Recoleta ...
261,Round 1,25.01.2025,2 de Mayo,Nacional Asuncion,25.01.2025 | 2 de Mayo | Nacional Asuncion | 0...
262,Round 1,25.01.2025,Sp. Luqueno,Atl. Tembetary,25.01.2025 | Sp. Luqueno | Atl. Tembetary | 1 | 1
263,Round 1,24.01.2025,Sportivo Trinidense,Ameliano,24.01.2025 | Sportivo Trinidense | Ameliano | ...

In [26]:
# First do the checks, then do the filtering and removing of round prefix if necessary

check_rounds(df)
check_teams(df)
check_games(df)

Rounds: ['Round 22', 'Round 21', 'Round 20', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 15', 'Round 14', 'Round 13', 'Round 11', 'Round 12', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Sportivo Trinidense', 'Cerro Porteno', 'Olimpia Asuncion', 'Libertad Asuncion', 'Recoleta', 'General Caballero JLM', 'Atl. Tembetary', '2 de Mayo', 'Sp. Luqueno', 'Guarani', 'Ameliano', 'Nacional Asuncion'}
Number of teams: 12
All teams appear same amount of times in home and away: True
Each team appears 22 times in home and away
=== Game Balance Check ===

Head-to-head matrix:
                       2 de Mayo  Ameliano  Atl. Tembetary  Cerro Porteno  General Caballero JLM  Guarani  Libertad Asuncion  Nacional Asuncion  Olimpia Asuncion  Recoleta  Sp. Luqueno  Sportivo Trinidense
2 de Mayo                      0         4               4              4                      4        4                  4                  4                 4         4            4                    4
Ameliano                       4         0               4              4                      4        4                  4                  4                 4         4            4                    4
Atl. Tembetary                 4         4               0              4                      4        4                  4                  4                 4         4            4                    4
Cerro Porteno                  4         4               4              0                      4        4                  4                  4                 4         4            4                    4
General Caballero JLM          4         4               4              4                      0        4                  4                  4                 4         4            4                    4
Guarani                        4         4               4              4                      4        0                  4                  4                 4         4            4                    4
Libertad Asuncion              4         4               4              4                      4        4                  0                  4                 4         4            4                    4
Nacional Asuncion              4         4               4              4                      4        4                  4                  0                 4         4            4                    4
Olimpia Asuncion               4         4               4              4                      4        4                  4                  4                 0         4            4                    4
Recoleta                       4         4               4              4                      4        4                  4                  4                 4         0            4                    4
Sp. Luqueno                    4         4               4              4                      4        4                  4                  4                 4         4            0                    4
Sportivo Trinidense            4         4               4              4                      4        4                  4                  4                 4         4            4                    0

Balanced: every pair plays exactly 4 time(s).

In [95]:
# write away cleaned df and adapt logboek
df = remove_round_prefix(df)
df.to_csv(f"./cleaned_data/{filename}", index=False)

In [27]:
df_only_rounds = filter_rounds(df)

In [116]:
check_rounds(df_only_rounds)
check_teams(df_only_rounds)
check_games(df_only_rounds)

Rounds: ['Round 30', 'Round 29', 'Round 28', 'Round 27', 'Round 26', 'Round 25', 'Round 24', 'Round 23', 'Round 22', 'Round 21', 'Round 20', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 6', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Elfsborg', 'Oster', 'Degerfors', 'Sirius', 'Goteborg', 'Hacken', 'Norrkoping', 'GAIS', 'Brommapojkarna', 'Varnamo', 'Halmstad', 'AIK', 'Malmo FF', 'Mjallby', 'Djurgarden', 'Hammarby'}
Number of teams: 16
All teams appear same amount of times in home and away: True
Each team appears 15 times in home and away
=== Game Balance Check ===

Head-to-head matrix:
                AIK  Brommapojkarna  Degerfors  Djurgarden  Elfsborg  GAIS  Goteborg  Hacken  Halmstad  Hammarby  Malmo FF  Mjallby  Norrkoping  Oster  Sirius  Varnamo
AIK               0               2          2           2         2     2         2       2         2         2         2        2           2      2       2        2
Brommapojkarna    2               0          2           2         2     2         2       2         2         2         2        2           2      2       2        2
Degerfors         2               2          0           2         2     2         2       2         2         2         2        2           2      2       2        2
Djurgarden        2               2          2           0         2     2         2       2         2         2         2        2           2      2       2        2
Elfsborg          2               2          2           2         0     2         2       2         2         2         2        2           2      2       2        2
GAIS              2               2          2           2         2     0         2       2         2         2         2        2           2      2       2        2
Goteborg          2               2          2           2         2     2         0       2         2         2         2        2           2      2       2        2
Hacken            2               2          2           2         2     2         2       0         2         2         2        2           2      2       2        2
Halmstad          2               2          2           2         2     2         2       2         0         2         2        2           2      2       2        2
Hammarby          2               2          2           2         2     2         2       2         2         0         2        2           2      2       2        2
Malmo FF          2               2          2           2         2     2         2       2         2         2         0        2           2      2       2        2
Mjallby           2               2          2           2         2     2         2       2         2         2         2        0           2      2       2        2
Norrkoping        2               2          2           2         2     2         2       2         2         2         2        2           0      2       2        2
Oster             2               2          2           2         2     2         2       2         2         2         2        2           2      0       2        2
Sirius            2               2          2           2         2     2         2       2         2         2         2        2           2      2       0        2
Varnamo           2               2          2           2         2     2         2       2         2         2         2        2           2      2       2        0

Balanced: every pair plays exactly 2 time(s).

In [117]:
# write away cleaned df and adapt logboek
df_only_rounds = remove_round_prefix(df_only_rounds)
df_only_rounds.to_csv(f"./cleaned_data/{filename}", index=False)

In [111]:
df_only_rounds = filter_playoffs(df_only_rounds, 31)

In [86]:
df_only_rounds

,round,date,team_home,team_away,full_text
0,Round 33,21.04.2025,Basel,Yverdon,21.04.2025 | Basel | Yverdon | 5 | 0
1,Round 33,21.04.2025,Lausanne,Lugano,21.04.2025 | Lausanne | Lugano | 2 | 0
2,Round 33,21.04.2025,Servette,Luzern,21.04.2025 | Servette | Luzern | 2 | 1
3,Round 33,21.04.2025,St. Gallen,Sion,21.04.2025 | St. Gallen | Sion | 1 | 0
4,Round 33,21.04.2025,Young Boys,Zurich,21.04.2025 | Young Boys | Zurich | 2 | 1
...,...,...,...,...,...
193,Round 1,21.07.2024,Luzern,Servette,21.07.2024 | Luzern | Servette | 1 | 2
194,Round 1,21.07.2024,Young Boys,Sion,21.07.2024 | Young Boys | Sion | 1 | 2
195,Round 1,20.07.2024,Winterthur,St. Gallen,20.07.2024 | Winterthur | St. Gallen | 1 | 0
196,Round 1,20.07.2024,Lugano,Grasshoppers,20.07.2024 | Lugano | Grasshoppers | 2 | 1
197,Round 1,20.07.2024,Yverdon,Zurich,20.07.2024 | Yverdon | Zurich | 0 | 2

In [62]:
df_only_rounds[df_only_rounds["round"] == "Round 1"]

Empty DataFrame
Columns: [round, date, team_home, team_away, full_text]
Index: []

In [28]:
df_filtered = filter_on_date(df_only_rounds, "2025-07-03", keep_before=False)

C:\Users\simcosyn\AppData\Local\Temp\ipykernel_10428\1965196199.py:8: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return_df["date"] = pd.to_datetime(return_df["date"], errors='coerce')

In [29]:
df_filtered

,round,date,team_home,team_away,full_text
0,Round 22,2025-11-30,Atl. Tembetary,Cerro Porteno,30.11.2025 | Atl. Tembetary | Cerro Porteno | ...
1,Round 22,2025-11-30,Guarani,Sp. Luqueno,30.11.2025 | Guarani | Sp. Luqueno | 2 | 1
2,Round 22,2025-11-28,Recoleta,Nacional Asuncion,28.11.2025 | Recoleta | Nacional Asuncion | 0 | 0
3,Round 22,2025-11-27,Libertad Asuncion,General Caballero JLM,27.11.2025 | Libertad Asuncion | General Cabal...
4,Round 22,2025-11-26,Olimpia Asuncion,2 de Mayo,26.11.2025 | Olimpia Asuncion | 2 de Mayo | 3 | 3
...,...,...,...,...,...
127,Round 1,2025-07-06,Guarani,2 de Mayo,06.07.2025 | Guarani | 2 de Mayo | 3 | 1
128,Round 1,2025-07-06,Olimpia Asuncion,Nacional Asuncion,06.07.2025 | Olimpia Asuncion | Nacional Asunc...
129,Round 1,2025-07-05,Libertad Asuncion,Sp. Luqueno,05.07.2025 | Libertad Asuncion | Sp. Luqueno |...
130,Round 1,2025-07-05,Cerro Porteno,General Caballero JLM,05.07.2025 | Cerro Porteno | General Caballero...
131,Round 1,2025-07-04,Recoleta,Sportivo Trinidense,04.07.2025 | Recoleta | Sportivo Trinidense | ...

In [30]:
check_rounds(df_filtered)
check_teams(df_filtered)   
check_games(df_filtered)

Rounds: ['Round 22', 'Round 21', 'Round 20', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 15', 'Round 14', 'Round 13', 'Round 11', 'Round 12', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Sportivo Trinidense', 'Cerro Porteno', 'Olimpia Asuncion', 'Libertad Asuncion', 'Recoleta', 'General Caballero JLM', 'Atl. Tembetary', '2 de Mayo', 'Sp. Luqueno', 'Guarani', 'Ameliano', 'Nacional Asuncion'}
Number of teams: 12
All teams appear same amount of times in home and away: True
Each team appears 11 times in home and away
=== Game Balance Check ===

Head-to-head matrix:
                       2 de Mayo  Ameliano  Atl. Tembetary  Cerro Porteno  General Caballero JLM  Guarani  Libertad Asuncion  Nacional Asuncion  Olimpia Asuncion  Recoleta  Sp. Luqueno  Sportivo Trinidense
2 de Mayo                      0         2               2              2                      2        2                  2                  2                 2         2            2                    2
Ameliano                       2         0               2              2                      2        2                  2                  2                 2         2            2                    2
Atl. Tembetary                 2         2               0              2                      2        2                  2                  2                 2         2            2                    2
Cerro Porteno                  2         2               2              0                      2        2                  2                  2                 2         2            2                    2
General Caballero JLM          2         2               2              2                      0        2                  2                  2                 2         2            2                    2
Guarani                        2         2               2              2                      2        0                  2                  2                 2         2            2                    2
Libertad Asuncion              2         2               2              2                      2        2                  0                  2                 2         2            2                    2
Nacional Asuncion              2         2               2              2                      2        2                  2                  0                 2         2            2                    2
Olimpia Asuncion               2         2               2              2                      2        2                  2                  2                 0         2            2                    2
Recoleta                       2         2               2              2                      2        2                  2                  2                 2         0            2                    2
Sp. Luqueno                    2         2               2              2                      2        2                  2                  2                 2         2            0                    2
Sportivo Trinidense            2         2               2              2                      2        2                  2                  2                 2         2            2                    0

Balanced: every pair plays exactly 2 time(s).

In [31]:
df_filtered = remove_round_prefix(df_filtered)
df_filtered.to_csv(f"./cleaned_data/{filename}", index=False)