### Inspect scraped data_files

In [3]:
import pandas as pd

In [4]:
logboek_df = pd.read_csv('logboek.csv', sep=';')
countries = logboek_df["land"].tolist()
leagues = logboek_df["competitienaam"].tolist()
seasons = logboek_df["jaar"].tolist()

In [5]:
print(countries)

['england', 'mexico', 'japan', 'iran', 'south-korea', 'australia', 'morocco', 'senegal', 'nigeria', 'algeria', 'egypt', 'ivory-coast', 'usa', 'canada', 'panama', 'argentina', 'brazil', 'colombia', 'uruguay', 'ecuador', 'paraguay', 'austria', 'belgium', 'cyprus', 'czech-republic', 'france', 'germany', 'hungary', 'ireland', 'italy', 'luxembourg', 'malta', 'netherlands', 'northern-ireland', 'norway', 'poland', 'portugal', 'romania', 'russia', 'scotland', 'slovakia', 'spain', 'switzerland', 'turkey', 'wales', 'croatia', 'denmark', 'ukraine', 'serbia', 'sweden']

### checked up untill index 0

In [27]:
def filter_rounds(df):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str.startswith("Round ")].reset_index(drop=True)
    return return_df

In [55]:
def filter_playoffs(df, start_round_playoffs):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str[6:].astype(int) < start_round_playoffs].reset_index(drop=True)
    return return_df

In [28]:
def filter_on_date(df, start_date):
    """ 
    Format start_date: "YYYY-MM-DD"
    """
    return_df = df.copy()
    start_date = pd.to_datetime(start_date)
    
    return_df["date"] = pd.to_datetime(return_df["date"], errors='coerce')
    return_df = return_df[(return_df["date"] >= start_date)].reset_index(drop=True)
    return return_df

In [8]:
def remove_round_prefix(df):
    return_df = df.copy()
    return_df["round"] = return_df["round"].apply(lambda x: x[6:])
    return return_df

In [9]:
def check_rounds(df):
    rounds = df["round"].unique().tolist()
    counted_rounds = df["round"].value_counts().to_dict()

    # check if all rounds appear the same amount of times
    rounds_appear_same_amount = len(set(counted_rounds.values())) == 1

    # check if rounds start with "Round"
    rounds_start_with_round = all(r.startswith("Round") for r in rounds)

    print(f"Rounds: {rounds}")
    print(f"Only normal rounds: {rounds_start_with_round}")
    print(f"All rounds appear same amount of times: {rounds_appear_same_amount}")

In [10]:
def check_teams(df):
    home_teams = df["team_home"].unique().tolist()
    away_teams = df["team_away"].unique().tolist()

    all_teams = set(home_teams) | set(away_teams)
    print(f"Teams: {all_teams}")
    print(f"Number of teams: {len(all_teams)}")

    # check if all teams appear in both home and away the same amount of times
    home_team_counts = df["team_home"].value_counts().to_dict()
    away_team_counts = df["team_away"].value_counts().to_dict()
    teams_appear_same_amount = all(home_team_counts.get(team, 0) == away_team_counts.get(team, 0) for team in all_teams)
    print(f"All teams appear same amount of times in home and away: {teams_appear_same_amount}")
    if teams_appear_same_amount:
        print(f"Each team appears {home_team_counts[home_teams[0]]} times in home and away")

In [ ]:
# Checked untill index 4, south-korea
index = 4
country = countries[index]
league = leagues[index]
season = seasons[index]
print(country)
print(league)
print(season)
filename = f"{country}_{league}_{season}.csv"
df = pd.read_csv(f"./scraped_data/{filename}")
df.head()

south-korea
k-league-1
2025

,round,date,team_home,team_away,full_text
0,Final,08.12.2025,Suwon FC,Bucheon FC 1995,08.12.2025 | Suwon FC | Bucheon FC 1995 | Winn...
1,Final,07.12.2025,Jeju SK,Advancing to next round: Jeju SK,07.12.2025 | Jeju SK | Advancing to next round...
2,Final,05.12.2025,Bucheon FC 1995,Suwon FC,05.12.2025 | Bucheon FC 1995 | Suwon FC | 1 | 0
3,Final,03.12.2025,Suwon Bluewings,Jeju SK,03.12.2025 | Suwon Bluewings | Jeju SK | 0 | 1
4,Round 38,30.11.2025,Gangwon,Pohang,30.11.2025 | Gangwon | Pohang | 1 | 0

In [42]:
# First do the checks, then do the filtering and removing of round prefix if necessary

check_rounds(df)
check_teams(df)

Rounds: ['Round 30', 'Round 29', 'Round 28', 'Round 22', 'Round 27', 'Round 26', 'Round 25', 'Round 24', 'Round 23', 'Round 21', 'Round 20', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 8', 'Round 11', 'Round 4', 'Round 10', 'Round 9', 'Round 7', 'Round 6', 'Round 5', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Persepolis', 'Gol Gohar', 'Sepahan', 'Chadormalu', 'Esteghlal Khuzestan', 'Shams Azar Qazvin', 'Foolad', 'Aluminium Arak', 'Malavan', 'Esteghlal F.C.', 'Havadar SC', 'Zob Ahan', 'Mes Rafsanjan', 'Kheybar Khorramabad', 'Nassaji Mazandaran', 'Tractor'}
Number of teams: 16
All teams appear same amount of times in home and away: True
Each team appears 15 times in home and away

In [47]:
df_only_rounds = filter_rounds(df)

In [58]:
check_rounds(df_only_rounds)
check_teams(df_only_rounds)

Rounds: ['Round 33', 'Round 32', 'Round 31', 'Round 30', 'Round 29', 'Round 28', 'Round 27', 'Round 26', 'Round 25', 'Round 20', 'Round 24', 'Round 23', 'Round 22', 'Round 21', 'Round 19', 'Round 18', 'Round 17', 'Round 16', 'Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 4', 'Round 5', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Ulsan HD', 'Daegu', 'Gangwon', 'Daejeon', 'Suwon FC', 'Seoul', 'Jeonbuk', 'Anyang', 'Jeju SK', 'Gwangju FC', 'Pohang', 'Gimcheon Sangmu'}
Number of teams: 12
All teams appear same amount of times in home and away: False

In [60]:
print(df_only_rounds.value_counts("team_home"))
print(df_only_rounds.value_counts("team_away"))

team_home
Anyang             17
Jeonbuk            17
Seoul              17
Gangwon            17
Gimcheon Sangmu    17
Pohang             17
Daegu              16
Daejeon            16
Ulsan HD           16
Suwon FC           16
Gwangju FC         16
Jeju SK            16
Name: count, dtype: int64
team_away
Jeju SK            17
Suwon FC           17
Gwangju FC         17
Ulsan HD           17
Daejeon            17
Daegu              17
Gimcheon Sangmu    16
Gangwon            16
Pohang             16
Anyang             16
Seoul              16
Jeonbuk            16
Name: count, dtype: int64

In [56]:
df_only_rounds = filter_playoffs(df_only_rounds, 34)

In [63]:
df_only_rounds

,round,date,team_home,team_away,full_text
0,33,18.10.2025,Anyang,Gimcheon Sangmu,18.10.2025 | Anyang | Gimcheon Sangmu | 4 | 1
1,33,18.10.2025,Daegu,Gangwon,18.10.2025 | Daegu | Gangwon | 2 | 2
2,33,18.10.2025,Daejeon,Jeju SK,18.10.2025 | Daejeon | Jeju SK | 3 | 1
3,33,18.10.2025,Jeonbuk,Suwon FC,18.10.2025 | Jeonbuk | Suwon FC | 2 | 0
4,33,18.10.2025,Seoul,Pohang,18.10.2025 | Seoul | Pohang | 1 | 2
...,...,...,...,...,...
193,1,16.02.2025,Jeonbuk,Gimcheon Sangmu,16.02.2025 | Jeonbuk | Gimcheon Sangmu | 2 | 1
194,1,16.02.2025,Ulsan HD,Anyang,16.02.2025 | Ulsan HD | Anyang | 0 | 1
195,1,15.02.2025,Gwangju FC,Suwon FC,15.02.2025 | Gwangju FC | Suwon FC | 0 | 0
196,1,15.02.2025,Jeju SK,Seoul,15.02.2025 | Jeju SK | Seoul | 2 | 0
197,1,15.02.2025,Pohang,Daejeon,15.02.2025 | Pohang | Daejeon | 0 | 3

In [62]:
df_only_rounds[df_only_rounds["round"] == "Round 1"]

Empty DataFrame
Columns: [round, date, team_home, team_away, full_text]
Index: []

In [33]:
df_filtererd = filter_on_date(df_only_rounds, "2025-01-11")

C:\Users\simcosyn\AppData\Local\Temp\ipykernel_24252\3222430827.py:8: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return_df["date"] = pd.to_datetime(return_df["date"], errors='coerce')

In [34]:
df_filtererd

,round,date,team_home,team_away,full_text
0,Round 17,2025-04-21,Juarez,Queretaro,21.04.2025 | Juarez | Queretaro | 0 | 2
1,Round 17,2025-04-21,Club Leon,Monterrey,21.04.2025 | Club Leon | Monterrey | 0 | 2
2,Round 17,2025-04-21,Atl. San Luis,Pachuca,21.04.2025 | Atl. San Luis | Pachuca | 2 | 1
3,Round 17,2025-04-21,Santos Laguna,Club Tijuana,21.04.2025 | Santos Laguna | Club Tijuana | 0 | 4
4,Round 17,2025-04-20,Atlas,Guadalajara Chivas,20.04.2025 | Atlas | Guadalajara Chivas | 1 | 1
...,...,...,...,...,...
148,Round 1,2025-01-12,Guadalajara Chivas,Santos Laguna,12.01.2025 | Guadalajara Chivas | Santos Lagun...
149,Round 1,2025-01-12,Atl. San Luis,Tigres UANL,12.01.2025 | Atl. San Luis | Tigres UANL | 1 | 3
150,Round 1,2025-01-11,Club Tijuana,Toluca,11.01.2025 | Club Tijuana | Toluca | 2 | 4
151,Round 1,2025-01-11,Mazatlan FC,Juarez,11.01.2025 | Mazatlan FC | Juarez | 1 | 1
152,Round 1,2025-01-11,Queretaro,Club America,11.01.2025 | Queretaro | Club America | 0 | 1

In [61]:
df_only_rounds = remove_round_prefix(df_only_rounds)

In [64]:
# write away cleaned df and adapt logboek
df_only_rounds.to_csv(f"./cleaned_data/{filename}", index=False)