### Inspect scraped data_files

In [1]:
import pandas as pd
from itertools import combinations

In [2]:
logboek_df = pd.read_csv('logboek.csv', sep=';')
countries = logboek_df["land"].tolist()
leagues = logboek_df["competitienaam"].tolist()
seasons = logboek_df["jaar"].tolist()

In [32]:
import os

folder_path = './cleaned_data/'
file_count = 0

# os.walk goes through every directory and subdirectory
for root, dirs, files in os.walk(folder_path):
    file_count += len(files)

print(f"Total files including subfolders: {file_count}")

Total files including subfolders: 49

In [52]:
ac_indexes = [1,14]

for index in ac_indexes:
    country = countries[index]
    league = leagues[index]
    season = seasons[index]
    print(country)
    print(league)
    print(season)
    filename = f"{country}_{league}_{season}"
    df = pd.read_csv(f"./cleaned_data/{filename}.csv_A")
    df.to_csv(f"./cleaned_data/{filename}_A.csv", index=False)

mexico
liga-mx
2024-2025
panama
lpf
2025

In [3]:
print(countries)

['england', 'mexico', 'japan', 'iran', 'south-korea', 'australia', 'morocco', 'senegal', 'nigeria', 'algeria', 'egypt', 'ivory-coast', 'usa', 'canada', 'panama', 'argentina', 'brazil', 'colombia', 'uruguay', 'ecuador', 'paraguay', 'austria', 'belgium', 'cyprus', 'czech-republic', 'france', 'germany', 'hungary', 'ireland', 'italy', 'luxembourg', 'malta', 'netherlands', 'northern-ireland', 'norway', 'poland', 'portugal', 'romania', 'russia', 'scotland', 'slovakia', 'spain', 'switzerland', 'turkey', 'wales', 'croatia', 'denmark', 'ukraine', 'serbia', 'sweden']

### checked up untill index 0

In [4]:
def filter_rounds(df):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str.startswith("Round ")].reset_index(drop=True)
    return return_df

In [5]:
def filter_playoffs(df, start_round_playoffs):
    return_df = df.copy()
    return_df = return_df[return_df["round"].str[6:].astype(int) < start_round_playoffs].reset_index(drop=True)
    return return_df

In [6]:
def filter_on_date(df, start_date, keep_before = True):
    """ 
    Format start_date: "YYYY-MM-DD"
    """
    return_df = df.copy()
    start_date = pd.to_datetime(start_date)
    
    return_df["date"] = pd.to_datetime(return_df["date"], format="%d.%m.%Y", errors='coerce')
    
    if keep_before:
        return_df = return_df[(return_df["date"] < start_date)].reset_index(drop=True)
    else:
        return_df = return_df[(return_df["date"] >= start_date)].reset_index(drop=True)
    return return_df

In [7]:
def fill_in_forfaits(df):
    return_df = df.copy()
    
    forfait_indices = return_df[return_df["team_home"] == "Awrd"].index
    
    for idx in forfait_indices:
        parts = return_df.loc[idx, "full_text"].split(" | ")
        return_df.loc[idx, "team_home"] = parts[2]
        return_df.loc[idx, "team_away"] = parts[3]
    
    return return_df

In [8]:
def remove_round_prefix(df):
    return_df = df.copy()
    return_df["round"] = return_df["round"].apply(lambda x: x[6:])
    return return_df

In [9]:
def check_specific_match(df, team1, team2):
    return df[((df["team_home"] == team1) & (df["team_away"] == team2)) | ((df["team_home"] == team2) & (df["team_away"] == team1))]

In [10]:
def check_rounds(df):
    rounds = df["round"].unique().tolist()
    counted_rounds = df["round"].value_counts().to_dict()

    # check if all rounds appear the same amount of times
    rounds_appear_same_amount = len(set(counted_rounds.values())) == 1

    # check if rounds start with "Round"
    rounds_start_with_round = all(r.startswith("Round") for r in rounds)

    print(f"Rounds: {rounds}")
    print(f"Only normal rounds: {rounds_start_with_round}")
    print(f"All rounds appear same amount of times: {rounds_appear_same_amount}")

In [11]:
def check_teams(df):
    home_teams = df["team_home"].unique().tolist()
    away_teams = df["team_away"].unique().tolist()

    all_teams = set(home_teams) | set(away_teams)
    print(f"Teams: {all_teams}")
    print(f"Number of teams: {len(all_teams)}")

    # check if all teams appear in both home and away the same amount of times
    home_team_counts = df["team_home"].value_counts().to_dict()
    away_team_counts = df["team_away"].value_counts().to_dict()
    teams_appear_same_amount = all(home_team_counts.get(team, 0) == away_team_counts.get(team, 0) for team in all_teams)
    print(f"All teams appear same amount of times in home and away: {teams_appear_same_amount}")
    if teams_appear_same_amount:
        print(f"Each team appears {home_team_counts[home_teams[0]]} times in home and away")
    elif len(all_teams) % 2 == 0:
        rand_team = list(all_teams)[0]
        expected_h_games = (home_team_counts[rand_team] + away_team_counts[rand_team]) / 2
        print("Teams that don't play the expected amount at home")
        for key, value in home_team_counts.items():
            if value != expected_h_games:
                print(f"{key}: {value}")
        
        print()
        print("Amount of times teams played away")
        for key, value in away_team_counts.items():
           if value != expected_h_games:
                print(f"{key}: {value}")
    
    else:
        print(f"Odd number of teams: {len(all_teams)}")

In [12]:
def check_games(df):
    teams = sorted(set(df['team_home'].unique()) | set(df['team_away'].unique()))
    
    # Build symmetric n x n matrix
    matrix = pd.DataFrame(0, index=teams, columns=teams)
    
    for _, row in df.iterrows():
        h, a = row['team_home'], row['team_away']
        matrix.loc[h, a] += 1
        matrix.loc[a, h] += 1  # symmetric: home/away doesn't matter
    
    # Extract counts for all unique pairs (upper triangle)
    pair_counts = {
        (t1, t2): matrix.loc[t1, t2]
        for t1, t2 in combinations(teams, 2)
    }
    
    unique_counts = set(pair_counts.values())
    is_balanced = len(unique_counts) == 1 and 0 not in unique_counts
    
    print("=== Game Balance Check ===\n")
    print("Head-to-head matrix:")
    print(matrix.to_string())
    print()
    
    count_freq = {}
    for v in pair_counts.values():
        count_freq[v] = count_freq.get(v, 0) + 1
    
    if is_balanced:
        times = unique_counts.pop()
        print(f"Balanced: every pair plays exactly {times} time(s).")
    else:
        print(f"Not balanced. Distribution of matchup counts: {count_freq}")
        if 0 in unique_counts:
            missing = [f"{t1} vs {t2}" for (t1, t2), v in pair_counts.items() if v == 0]
            print(f"   Never played: {missing[:10]}{'...' if len(missing) > 10 else ''}")
        modal = max(set(pair_counts.values()), key=list(pair_counts.values()).count)
        odd = {f"{k[0]} vs {k[1]}": v for k, v in pair_counts.items() if v != modal}
        if odd:
            print(f"   Odd counts: {odd}")

In [107]:
# Checked untill index 10, egypt
index = 18
country = countries[index]
league = leagues[index]
season = seasons[index]
print(country)
print(league)
print(season)
filename = f"{country}_{league}_{season}"
df = pd.read_csv(f"./scraped_data/{filename}.csv")
df = fill_in_forfaits(df)
df

uruguay
liga-auf-uruguaya
2025

,round,date,team_home,team_away,full_text
0,Final,30.11.2025,AET,Nacional,30.11.2025 | AET | Nacional | Winner: Nacional...
1,Final,23.11.2025,Penarol,Nacional,23.11.2025 | Penarol | Nacional | 2 | 2
2,Semi-finals,16.11.2025,AET,Liverpool M.,16.11.2025 | AET | Liverpool M. | Penarol | Ad...
3,Round 15,09.11.2025,Defensor Sp.,Nacional,09.11.2025 | Defensor Sp. | Nacional | 1 | 1
4,Round 15,09.11.2025,Juventud,Progreso,09.11.2025 | Juventud | Progreso | 1 | 1
...,...,...,...,...,...
295,Round 1,02.02.2025,Miramar,Plaza Colonia,02.02.2025 | Miramar | Plaza Colonia | 0 | 1
296,Round 1,02.02.2025,Progreso,Penarol,02.02.2025 | Progreso | Penarol | 1 | 3
297,Round 1,01.02.2025,Danubio,Liverpool M.,01.02.2025 | Danubio | Liverpool M. | 1 | 1
298,Round 1,01.02.2025,Defensor Sp.,Boston River,01.02.2025 | Defensor Sp. | Boston River | 2 | 0
299,Round 1,31.01.2025,Cerro Largo,Juventud,31.01.2025 | Cerro Largo | Juventud | 1 | 1

In [97]:
# First do the checks, then do the filtering and removing of round prefix if necessary

check_rounds(df)
check_teams(df)
check_games(df)

Rounds: ['Final', 'Semi-finals', 'Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: False
All rounds appear same amount of times: False
Teams: {'Juventud', 'Cerro Largo', 'Miramar', 'Boston River', 'CA Cerro', 'River Plate', 'Penarol', 'Pen', 'Montevideo City', 'Progreso', 'AET', 'Wanderers', 'Racing Montevideo', 'Danubio', 'Plaza Colonia', 'Defensor Sp.', 'Liverpool M.', 'Nacional'}
Number of teams: 18
All teams appear same amount of times in home and away: False
Teams that don't play the expected amount at home
Penarol: 20
Defensor Sp.: 19
Juventud: 19
Cerro Largo: 19
Racing Montevideo: 19
Liverpool M.: 19
Nacional: 19
Boston River: 19
Montevideo City: 18
CA Cerro: 18
Wanderers: 18
Danubio: 18
Miramar: 18
Plaza Colonia: 18
River Plate: 18
Progreso: 18
AET: 2
Pen: 1

Amount of times teams played away
Nacional: 20
Liverpool M.: 19
Progreso: 19
Penarol: 19
River Plate: 19
Plaza Colonia: 19
Danubio: 19
Miramar: 19
Montevideo City: 19
Wanderers: 19
CA Cerro: 19
Boston River: 18
Racing Montevideo: 18
Cerro Largo: 18
Defensor Sp.: 18
Juventud: 18
=== Game Balance Check ===

Head-to-head matrix:
                   AET  Boston River  CA Cerro  Cerro Largo  Danubio  Defensor Sp.  Juventud  Liverpool M.  Miramar  Montevideo City  Nacional  Pen  Penarol  Plaza Colonia  Progreso  Racing Montevideo  River Plate  Wanderers
AET                  0             0         0            0        0             0         0             1        0                0         1    0        0              0         0                  0            0          0
Boston River         0             0         2            2        3             2         3             2        3                3         3    0        2              2         3                  3            2          2
CA Cerro             0             2         0            3        2             3         2             3        2                2         2    0        3              3         2                  2            3          3
Cerro Largo          0             2         3            0        2             3         2             3        2                2         2    0        3              3         2                  2            3          3
Danubio              0             3         2            2        0             2         3             2        3                3         3    0        2              2         3                  3            2          2
Defensor Sp.         0             2         3            3        2             0         2             3        2                2         2    0        3              3         2                  2            3          3
Juventud             0             3         2            2        3             2         0             2        3                3         3    0        2              2         3                  3            2          2
Liverpool M.         1             2         3            3        2             3         2             0        2                2         2    0        3              3         2                  2            3          3
Miramar              0             3         2            2        3             2         3             2        0                3         3    0        2              2         3                  3            2          2
Montevideo City      0             3         2            2        3             2         3             2        3                0         3    0        2              2         3                  3            2          2
Nacional             1             3         2            2        3             2         3             2        3                3         0    0        3              2         3                  3            2          2
Pen                  0             0         0            0        0             0         0             0        0                0         0    0        1              0         0                  0            0          0
Penarol              0             2         3            3        2             3         2             3        2                2         3    1        0              3         2                  2            3          3
Plaza Colonia        0             2         3            3        2             3         2             3        2                2         2    0        3              0         2                  2            3          3
Progreso             0             3         2            2        3             2         3             2        3                3         3    0        2              2         0                  3            2          2
Racing Montevideo    0             3         2            2        3             2         3             2        3                3         3    0        2              2         3                  0            2          2
River Plate          0             2         3            3        2             3         2             3        2                2         2    0        3              3         2                  2            0          3
Wanderers            0             2         3            3        2             3         2             3        2                2         2    0        3              3         2                  2            3          0

Not balanced. Distribution of matchup counts: {np.int64(0): 30, np.int64(1): 3, np.int64(2): 63, np.int64(3): 57}
   Never played: ['AET vs Boston River', 'AET vs CA Cerro', 'AET vs Cerro Largo', 'AET vs Danubio', 'AET vs Defensor Sp.', 'AET vs Juventud', 'AET vs Miramar', 'AET vs Montevideo City', 'AET vs Pen', 'AET vs Penarol']...
   Odd counts: {'AET vs Boston River': np.int64(0), 'AET vs CA Cerro': np.int64(0), 'AET vs Cerro Largo': np.int64(0), 'AET vs Danubio': np.int64(0), 'AET vs Defensor Sp.': np.int64(0), 'AET vs Juventud': np.int64(0), 'AET vs Liverpool M.': np.int64(1), 'AET vs Miramar': np.int64(0), 'AET vs Montevideo City': np.int64(0), 'AET vs Nacional': np.int64(1), 'AET vs Pen': np.int64(0), 'AET vs Penarol': np.int64(0), 'AET vs Plaza Colonia': np.int64(0), 'AET vs Progreso': np.int64(0), 'AET vs Racing Montevideo': np.int64(0), 'AET vs River Plate': np.int64(0), 'AET vs Wanderers': np.int64(0), 'Boston River vs Danubio': np.int64(3), 'Boston River vs Juventud': np.int64(3), 'Boston River vs Miramar': np.int64(3), 'Boston River vs Montevideo City': np.int64(3), 'Boston River vs Nacional': np.int64(3), 'Boston River vs Pen': np.int64(0), 'Boston River vs Progreso': np.int64(3), 'Boston River vs Racing Montevideo': np.int64(3), 'CA Cerro vs Cerro Largo': np.int64(3), 'CA Cerro vs Defensor Sp.': np.int64(3), 'CA Cerro vs Liverpool M.': np.int64(3), 'CA Cerro vs Pen': np.int64(0), 'CA Cerro vs Penarol': np.int64(3), 'CA Cerro vs Plaza Colonia': np.int64(3), 'CA Cerro vs River Plate': np.int64(3), 'CA Cerro vs Wanderers': np.int64(3), 'Cerro Largo vs Defensor Sp.': np.int64(3), 'Cerro Largo vs Liverpool M.': np.int64(3), 'Cerro Largo vs Pen': np.int64(0), 'Cerro Largo vs Penarol': np.int64(3), 'Cerro Largo vs Plaza Colonia': np.int64(3), 'Cerro Largo vs River Plate': np.int64(3), 'Cerro Largo vs Wanderers': np.int64(3), 'Danubio vs Juventud': np.int64(3), 'Danubio vs Miramar': np.int64(3), 'Danubio vs Montevideo City': np.int64(3), 'Danubio vs Nacional': np.int64(3), 'Danubio vs Pen': np.int64(0), 'Danubio vs Progreso': np.int64(3), 'Danubio vs Racing Montevideo': np.int64(3), 'Defensor Sp. vs Liverpool M.': np.int64(3), 'Defensor Sp. vs Pen': np.int64(0), 'Defensor Sp. vs Penarol': np.int64(3), 'Defensor Sp. vs Plaza Colonia': np.int64(3), 'Defensor Sp. vs River Plate': np.int64(3), 'Defensor Sp. vs Wanderers': np.int64(3), 'Juventud vs Miramar': np.int64(3), 'Juventud vs Montevideo City': np.int64(3), 'Juventud vs Nacional': np.int64(3), 'Juventud vs Pen': np.int64(0), 'Juventud vs Progreso': np.int64(3), 'Juventud vs Racing Montevideo': np.int64(3), 'Liverpool M. vs Pen': np.int64(0), 'Liverpool M. vs Penarol': np.int64(3), 'Liverpool M. vs Plaza Colonia': np.int64(3), 'Liverpool M. vs River Plate': np.int64(3), 'Liverpool M. vs Wanderers': np.int64(3), 'Miramar vs Montevideo City': np.int64(3), 'Miramar vs Nacional': np.int64(3), 'Miramar vs Pen': np.int64(0), 'Miramar vs Progreso': np.int64(3), 'Miramar vs Racing Montevideo': np.int64(3), 'Montevideo City vs Nacional': np.int64(3), 'Montevideo City vs Pen': np.int64(0), 'Montevideo City vs Progreso': np.int64(3), 'Montevideo City vs Racing Montevideo': np.int64(3), 'Nacional vs Pen': np.int64(0), 'Nacional vs Penarol': np.int64(3), 'Nacional vs Progreso': np.int64(3), 'Nacional vs Racing Montevideo': np.int64(3), 'Pen vs Penarol': np.int64(1), 'Pen vs Plaza Colonia': np.int64(0), 'Pen vs Progreso': np.int64(0), 'Pen vs Racing Montevideo': np.int64(0), 'Pen vs River Plate': np.int64(0), 'Pen vs Wanderers': np.int64(0), 'Penarol vs Plaza Colonia': np.int64(3), 'Penarol vs River Plate': np.int64(3), 'Penarol vs Wanderers': np.int64(3), 'Plaza Colonia vs River Plate': np.int64(3), 'Plaza Colonia vs Wanderers': np.int64(3), 'Progreso vs Racing Montevideo': np.int64(3), 'River Plate vs Wanderers': np.int64(3)}

In [81]:
# write away cleaned df and adapt logboek
df = remove_round_prefix(df)
df.to_csv(f"./cleaned_data/{filename}", index=False)

In [108]:
df_only_rounds = filter_rounds(df)

In [101]:
check_rounds(df_only_rounds)
check_teams(df_only_rounds)
check_games(df_only_rounds)

Rounds: ['Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: False
Teams: {'Juventud', 'Cerro Largo', 'Miramar', 'Boston River', 'CA Cerro', 'River Plate', 'Penarol', 'Montevideo City', 'Progreso', 'Wanderers', 'Racing Montevideo', 'Danubio', 'Plaza Colonia', 'Defensor Sp.', 'Liverpool M.', 'Nacional'}
Number of teams: 16
All teams appear same amount of times in home and away: False
Teams that don't play the expected amount at home
Defensor Sp.: 19
Juventud: 19
Cerro Largo: 19
Penarol: 19
Racing Montevideo: 19
Liverpool M.: 19
Nacional: 19
Boston River: 19
Montevideo City: 18
CA Cerro: 18
Wanderers: 18
Danubio: 18
Miramar: 18
Plaza Colonia: 18
River Plate: 18
Progreso: 18

Amount of times teams played away
Progreso: 19
River Plate: 19
Plaza Colonia: 19
Danubio: 19
Miramar: 19
Montevideo City: 19
Wanderers: 19
CA Cerro: 19
Nacional: 18
Penarol: 18
Boston River: 18
Liverpool M.: 18
Racing Montevideo: 18
Cerro Largo: 18
Defensor Sp.: 18
Juventud: 18
=== Game Balance Check ===

Head-to-head matrix:
                   Boston River  CA Cerro  Cerro Largo  Danubio  Defensor Sp.  Juventud  Liverpool M.  Miramar  Montevideo City  Nacional  Penarol  Plaza Colonia  Progreso  Racing Montevideo  River Plate  Wanderers
Boston River                  0         2            2        3             2         3             2        3                3         3        2              2         3                  3            2          2
CA Cerro                      2         0            3        2             3         2             3        2                2         2        3              3         2                  2            3          3
Cerro Largo                   2         3            0        2             3         2             3        2                2         2        3              3         2                  2            3          3
Danubio                       3         2            2        0             2         3             2        3                3         3        2              2         3                  3            2          2
Defensor Sp.                  2         3            3        2             0         2             3        2                2         2        3              3         2                  2            3          3
Juventud                      3         2            2        3             2         0             2        3                3         3        2              2         3                  3            2          2
Liverpool M.                  2         3            3        2             3         2             0        2                2         2        3              3         2                  2            3          3
Miramar                       3         2            2        3             2         3             2        0                3         3        2              2         3                  3            2          2
Montevideo City               3         2            2        3             2         3             2        3                0         3        2              2         3                  3            2          2
Nacional                      3         2            2        3             2         3             2        3                3         0        2              2         3                  3            2          2
Penarol                       2         3            3        2             3         2             3        2                2         2        0              3         2                  2            3          3
Plaza Colonia                 2         3            3        2             3         2             3        2                2         2        3              0         2                  2            3          3
Progreso                      3         2            2        3             2         3             2        3                3         3        2              2         0                  3            2          2
Racing Montevideo             3         2            2        3             2         3             2        3                3         3        2              2         3                  0            2          2
River Plate                   2         3            3        2             3         2             3        2                2         2        3              3         2                  2            0          3
Wanderers                     2         3            3        2             3         2             3        2                2         2        3              3         2                  2            3          0

Not balanced. Distribution of matchup counts: {np.int64(2): 64, np.int64(3): 56}
   Odd counts: {'Boston River vs Danubio': np.int64(3), 'Boston River vs Juventud': np.int64(3), 'Boston River vs Miramar': np.int64(3), 'Boston River vs Montevideo City': np.int64(3), 'Boston River vs Nacional': np.int64(3), 'Boston River vs Progreso': np.int64(3), 'Boston River vs Racing Montevideo': np.int64(3), 'CA Cerro vs Cerro Largo': np.int64(3), 'CA Cerro vs Defensor Sp.': np.int64(3), 'CA Cerro vs Liverpool M.': np.int64(3), 'CA Cerro vs Penarol': np.int64(3), 'CA Cerro vs Plaza Colonia': np.int64(3), 'CA Cerro vs River Plate': np.int64(3), 'CA Cerro vs Wanderers': np.int64(3), 'Cerro Largo vs Defensor Sp.': np.int64(3), 'Cerro Largo vs Liverpool M.': np.int64(3), 'Cerro Largo vs Penarol': np.int64(3), 'Cerro Largo vs Plaza Colonia': np.int64(3), 'Cerro Largo vs River Plate': np.int64(3), 'Cerro Largo vs Wanderers': np.int64(3), 'Danubio vs Juventud': np.int64(3), 'Danubio vs Miramar': np.int64(3), 'Danubio vs Montevideo City': np.int64(3), 'Danubio vs Nacional': np.int64(3), 'Danubio vs Progreso': np.int64(3), 'Danubio vs Racing Montevideo': np.int64(3), 'Defensor Sp. vs Liverpool M.': np.int64(3), 'Defensor Sp. vs Penarol': np.int64(3), 'Defensor Sp. vs Plaza Colonia': np.int64(3), 'Defensor Sp. vs River Plate': np.int64(3), 'Defensor Sp. vs Wanderers': np.int64(3), 'Juventud vs Miramar': np.int64(3), 'Juventud vs Montevideo City': np.int64(3), 'Juventud vs Nacional': np.int64(3), 'Juventud vs Progreso': np.int64(3), 'Juventud vs Racing Montevideo': np.int64(3), 'Liverpool M. vs Penarol': np.int64(3), 'Liverpool M. vs Plaza Colonia': np.int64(3), 'Liverpool M. vs River Plate': np.int64(3), 'Liverpool M. vs Wanderers': np.int64(3), 'Miramar vs Montevideo City': np.int64(3), 'Miramar vs Nacional': np.int64(3), 'Miramar vs Progreso': np.int64(3), 'Miramar vs Racing Montevideo': np.int64(3), 'Montevideo City vs Nacional': np.int64(3), 'Montevideo City vs Progreso': np.int64(3), 'Montevideo City vs Racing Montevideo': np.int64(3), 'Nacional vs Progreso': np.int64(3), 'Nacional vs Racing Montevideo': np.int64(3), 'Penarol vs Plaza Colonia': np.int64(3), 'Penarol vs River Plate': np.int64(3), 'Penarol vs Wanderers': np.int64(3), 'Plaza Colonia vs River Plate': np.int64(3), 'Plaza Colonia vs Wanderers': np.int64(3), 'Progreso vs Racing Montevideo': np.int64(3), 'River Plate vs Wanderers': np.int64(3)}

In [25]:
# write away cleaned df and adapt logboek
df_only_rounds = remove_round_prefix(df_only_rounds)
df_only_rounds.to_csv(f"./cleaned_data/{filename}", index=False)

In [23]:
df_only_rounds = filter_playoffs(df_only_rounds, 23)

In [ ]:
df_only_rounds[df_only_rounds["round"] == "Round 1"]

In [88]:
df_filtered = filter_on_date(df_only_rounds, "2025-05-23", keep_before=True)

In [109]:
df_filtered = filter_on_date(df_only_rounds, "2025-08-02", keep_before=False)

In [112]:
df_filtered = filter_on_date(df_only_rounds, "2025-07-06", keep_before=True)
df_filtered = filter_on_date(df_filtered, "2025-05-23", keep_before=False)

In [132]:
# DELETE MLS all stars
df_filtered = df_filtered[df_filtered["team_home"] != "MLS All-Stars"]

In [138]:
df_filtered

,round,date,team_home,team_away,full_text
0,1/8-finals,2025-10-18,Forge,Inter Toronto,18.10.2025 | Forge | Inter Toronto | 3 | 0
1,1/8-finals,2025-10-18,HFX Wanderers,Atl. Ottawa,18.10.2025 | HFX Wanderers | Atl. Ottawa | 0 | 1
2,1/8-finals,2025-10-18,Pacific FC,Valour,18.10.2025 | Pacific FC | Valour | 1 | 4
3,1/8-finals,2025-10-18,Vancouver FC,Cavalry,18.10.2025 | Vancouver FC | Cavalry | 2 | 2
4,1/8-finals,2025-10-12,Atl. Ottawa,Vancouver FC,12.10.2025 | Atl. Ottawa | Vancouver FC | 0 | 0
...,...,...,...,...,...
107,1/8-finals,2025-04-12,Pacific FC,Forge,12.04.2025 | Pacific FC | Forge | 0 | 2
108,1/8-finals,2025-04-07,Vancouver FC,Inter Toronto,07.04.2025 | Vancouver FC | Inter Toronto | 0 | 2
109,1/8-finals,2025-04-06,Pacific FC,Valour,06.04.2025 | Pacific FC | Valour | 2 | 0
110,1/8-finals,2025-04-05,Forge,Cavalry,05.04.2025 | Forge | Cavalry | 1 | 0
111,1/8-finals,2025-04-05,Atl. Ottawa,HFX Wanderers,05.04.2025 | Atl. Ottawa | HFX Wanderers | 2 | 2

In [110]:
check_rounds(df_filtered)
check_teams(df_filtered)   
check_games(df_filtered)

Rounds: ['Round 15', 'Round 14', 'Round 13', 'Round 12', 'Round 11', 'Round 10', 'Round 9', 'Round 8', 'Round 7', 'Round 6', 'Round 5', 'Round 4', 'Round 3', 'Round 2', 'Round 1']
Only normal rounds: True
All rounds appear same amount of times: True
Teams: {'Juventud', 'Cerro Largo', 'Miramar', 'Boston River', 'CA Cerro', 'River Plate', 'Penarol', 'Montevideo City', 'Progreso', 'Wanderers', 'Racing Montevideo', 'Danubio', 'Plaza Colonia', 'Defensor Sp.', 'Liverpool M.', 'Nacional'}
Number of teams: 16
All teams appear same amount of times in home and away: False
Teams that don't play the expected amount at home
Juventud: 8
Montevideo City: 8
CA Cerro: 8
Plaza Colonia: 8
Penarol: 8
Racing Montevideo: 8
River Plate: 8
Liverpool M.: 8
Defensor Sp.: 7
Wanderers: 7
Danubio: 7
Cerro Largo: 7
Miramar: 7
Progreso: 7
Nacional: 7
Boston River: 7

Amount of times teams played away
Nacional: 8
Progreso: 8
Boston River: 8
Cerro Largo: 8
Defensor Sp.: 8
Danubio: 8
Miramar: 8
Wanderers: 8
Penarol: 7
River Plate: 7
Plaza Colonia: 7
Liverpool M.: 7
Racing Montevideo: 7
Juventud: 7
Montevideo City: 7
CA Cerro: 7
=== Game Balance Check ===

Head-to-head matrix:
                   Boston River  CA Cerro  Cerro Largo  Danubio  Defensor Sp.  Juventud  Liverpool M.  Miramar  Montevideo City  Nacional  Penarol  Plaza Colonia  Progreso  Racing Montevideo  River Plate  Wanderers
Boston River                  0         1            1        1             1         1             1        1                1         1        1              1         1                  1            1          1
CA Cerro                      1         0            1        1             1         1             1        1                1         1        1              1         1                  1            1          1
Cerro Largo                   1         1            0        1             1         1             1        1                1         1        1              1         1                  1            1          1
Danubio                       1         1            1        0             1         1             1        1                1         1        1              1         1                  1            1          1
Defensor Sp.                  1         1            1        1             0         1             1        1                1         1        1              1         1                  1            1          1
Juventud                      1         1            1        1             1         0             1        1                1         1        1              1         1                  1            1          1
Liverpool M.                  1         1            1        1             1         1             0        1                1         1        1              1         1                  1            1          1
Miramar                       1         1            1        1             1         1             1        0                1         1        1              1         1                  1            1          1
Montevideo City               1         1            1        1             1         1             1        1                0         1        1              1         1                  1            1          1
Nacional                      1         1            1        1             1         1             1        1                1         0        1              1         1                  1            1          1
Penarol                       1         1            1        1             1         1             1        1                1         1        0              1         1                  1            1          1
Plaza Colonia                 1         1            1        1             1         1             1        1                1         1        1              0         1                  1            1          1
Progreso                      1         1            1        1             1         1             1        1                1         1        1              1         0                  1            1          1
Racing Montevideo             1         1            1        1             1         1             1        1                1         1        1              1         1                  0            1          1
River Plate                   1         1            1        1             1         1             1        1                1         1        1              1         1                  1            0          1
Wanderers                     1         1            1        1             1         1             1        1                1         1        1              1         1                  1            1          0

Balanced: every pair plays exactly 1 time(s).

In [75]:
check_specific_match(df_filtered, "Veraguas", "Tauro")

,round,date,team_home,team_away,full_text
53,Round 8,2025-09-13,Tauro,Veraguas,13.09.2025 | Tauro | Veraguas | 1 | 3

In [113]:
df_filtered = remove_round_prefix(df_filtered)
df_filtered.to_csv(f"./cleaned_data/{filename}_I.csv", index=False)

### MLS en Canada
werken niet met echte rondes. Meestal wel n_teams/2 aantal wedstrijden in weekend maar niet altijd en inhaalmatchen zijn ook niet direct duidelijk.

In [175]:
# checken of er rondes zijn.
# idee: ga door het df van onder naar boven. Als de volgende rij/wedstrijd max 1 dag later wordt gespeeld, dan is het waarschijnlijk dezelfde ronde. 
# Meer dan 1 dag later -> volgende ronde.
def impute_rounds(df, n_teams, date_threshold=2):
    return_df = df.copy()
    return_df["date"] = pd.to_datetime(return_df["date"], format="%Y-%m-%d", errors='coerce')
    return_df = return_df.sort_values("date").reset_index(drop=True)
    clubs = list(return_df["team_home"].unique())

    missing_teams_in_rounds = {}
    rounds = [1]  # first row is always Round 1
    rounds_dict = {1: 1}
    rounds_clubs = {1: set([return_df.loc[0, "team_home"], return_df.loc[0, "team_away"]])}
    current_round = 1
    for i in range(1, len(return_df)):
        date_diff = (return_df.loc[i, "date"] - return_df.loc[i-1, "date"]).days
        if date_diff > date_threshold:
            if rounds_dict[current_round] < n_teams / 2:
                missing_teams_in_rounds[current_round] = set(clubs) - rounds_clubs[current_round]
            current_round += 1
            
        rounds.append(current_round)
        rounds_dict[current_round] = rounds_dict.get(current_round, 0) + 1
        rounds_clubs[current_round] = rounds_clubs.get(current_round, set()) | set([return_df.loc[i, "team_home"], return_df.loc[i, "team_away"]])
    return_df["round"] = rounds
    return return_df

In [147]:
filename_can = "canada_canadian-premier-league_2025.csv"
filename_usa = "usa_mls_2025.csv"

In [159]:
df_can = pd.read_csv(f"./cleaned_data/{filename_can}")
df_usa = pd.read_csv(f"./cleaned_data/{filename_usa}")

In [178]:
df_rounds_can = impute_rounds(df_can, n_teams=8, date_threshold=1)

In [179]:
df_rounds_can["round"].value_counts()

round
1     4
3     4
4     4
5     4
9     4
10    4
13    4
14    4
18    4
19    4
20    4
22    4
23    4
24    4
25    4
26    4
27    4
28    4
29    4
30    4
31    4
32    4
33    4
2     3
6     3
8     3
12    3
15    3
7     1
11    1
16    1
17    1
21    1
Name: count, dtype: int64

In [169]:
impute_rounds(df_usa, 1)["round"].value_counts()

round
1     15
2     15
3     15
4     15
6     15
7     15
8     15
9     15
10    15
11    15
12    15
14    15
15    15
24    15
29    15
30    15
33    15
35    15
37    15
39    15
42    15
5     14
21    14
22    14
25    14
26    14
27    14
28    14
13    13
16    13
17    13
19    13
20    11
31    11
18     5
41     5
32     4
34     3
23     2
36     2
38     1
40     1
Name: count, dtype: int64